import {
  AdminMemberRecord,
  CollaboratorRecord,
  CompanyRecord,
  DeveloperSystemConfig,
  InterviewRecord,
  SectorRecord,
} from '../types';
import { CHROME_PRIORITY_WARNING } from './legalTerms';

export const DEFAULT_SYSTEM_CONFIG: DeveloperSystemConfig = {
  id: 'global_config',
  formTitle: 'ENTREVISTA COM GESTORES',
  formSubtitle: 'Formulário de Diagnóstico Organizacional',
  chromePriorityNotice: CHROME_PRIORITY_WARNING,
  pushNotificationsEnabled: true,
  sectionTitles: {
    1: '1. PLANEJAMENTO E DEMANDA',
    2: '2. CLIMA E CONFLITOS',
    3: '3. MUDANÇAS E INDICADORES',
    4: '4. PREVENÇÃO E MELHORIAS',
  },
  customQuestions: [
    {
      id: 'core_q1',
      sectionNumber: 1,
      questionNumber: 1,
      label: 'Quais são as principais demandas do setor e os períodos de maior pressão?',
      placeholder:
        'Descreva as entregas críticas, sazonalidades, fechamentos mensais e janelas de pico operacional...',
      required: true,
      isCore: true,
      coreKey: 'q1DemandsAndPressure',
    },
    {
      id: 'core_q2',
      sectionNumber: 1,
      questionNumber: 2,
      label: 'Como são distribuídas as tarefas e responsabilidades entre a equipe?',
      placeholder:
        'Explique os critérios de delegação, matriz de competências, rituais de alinhamento e balanceamento de carga...',
      required: true,
      isCore: true,
      coreKey: 'q2TaskDistribution',
    },
    {
      id: 'core_q3',
      sectionNumber: 2,
      questionNumber: 3,
      label: 'Quais conflitos são mais frequentes no dia a dia e como são tratados?',
      placeholder:
        'Relate divergências interpessoais ou intersetoriais recorrentes e os protocolos de mediação aplicados...',
      required: true,
      isCore: true,
      coreKey: 'q3FrequentConflicts',
    },
    {
      id: 'core_q4',
      sectionNumber: 2,
      questionNumber: 4,
      label: 'De que forma as reclamações e insatisfações da equipe são recebidas?',
      placeholder:
        'Detalhe os canais de escuta (1:1, reuniões, canal aberto), acolhimento e encaminhamento de feedbacks...',
      required: true,
      isCore: true,
      coreKey: 'q4ComplaintsHandling',
    },
    {
      id: 'core_q5',
      sectionNumber: 3,
      questionNumber: 5,
      label: 'Quais mudanças significativas ocorreram recentemente e qual foi o impacto?',
      placeholder:
        'Mencione reestruturações, novos sistemas, mudanças de liderança ou metas e como a equipe reagiu...',
      required: true,
      isCore: true,
      coreKey: 'q5SignificantChanges',
    },
    {
      id: 'core_q6',
      sectionNumber: 3,
      questionNumber: 6,
      label: 'Quais indicadores (absenteísmo, turnover, horas extras) chamam mais atenção?',
      placeholder:
        'Aponte as taxas atuais, desvios em relação à meta e fatores associados a faltas, rotatividade ou sobrejornada...',
      required: true,
      isCore: true,
      coreKey: 'q6AttentionIndicators',
    },
    {
      id: 'core_q7',
      sectionNumber: 4,
      questionNumber: 7,
      label: 'Quais medidas preventivas ou ações de melhoria já foram implantadas no setor?',
      placeholder:
        'Liste treinamentos, revisão de processos, pausas ergonômicas, contratações ou planos de ação em curso...',
      required: true,
      isCore: true,
      coreKey: 'q7PreventiveMeasures',
    },
  ],
  collaboratorCustomFields: [
    {
      id: 'cf_matricula',
      key: 'matriculaCorporativa',
      label: 'Matrícula Corporativa',
      type: 'text',
      placeholder: 'Ex: MAT-2026-089',
      required: false,
    },
    {
      id: 'cf_turno',
      key: 'turnoTrabalho',
      label: 'Turno / Regime de Trabalho',
      type: 'select',
      options: ['Comercial (08h às 18h)', 'Híbrido Corporativo', 'Turno 1 (06h às 14h)', 'Turno 2 (14h às 22h)', 'Remoto Integral'],
      required: false,
    },
    {
      id: 'cf_unidade',
      key: 'unidadeOperacional',
      label: 'Unidade / Filial',
      type: 'text',
      placeholder: 'Ex: Matriz São Paulo - SP',
      required: false,
    },
  ],
  ownerId: 'system_default',
};

export const INITIAL_COMPANIES: CompanyRecord[] = [
  {
    id: 'comp-horizonte-sa',
    name: 'Grupo Horizonte Engenharia & Logística S.A.',
    cnpj: '14.892.301/0001-45',
    segment: 'Logística Integrada e Infraestrutura',
    cityState: 'São Paulo / SP',
    registeredDate: '2026-09-10',
    ownerId: 'system_default',
  },
  {
    id: 'comp-vanguarda-tech',
    name: 'Vanguarda Soluções Industriais Ltda.',
    cnpj: '28.410.775/0001-90',
    segment: 'Manufatura Avançada & Automação',
    cityState: 'Campinas / SP',
    registeredDate: '2026-09-15',
    ownerId: 'system_default',
  },
  {
    id: 'comp-atlas-saude',
    name: 'Atlas Corporação Hospitalar & Diagnósticos',
    cnpj: '39.104.552/0001-12',
    segment: 'Saúde Corporativa e SST',
    cityState: 'Belo Horizonte / MG',
    registeredDate: '2026-09-20',
    ownerId: 'system_default',
  },
];

export const INITIAL_SECTORS: SectorRecord[] = [
  {
    id: 'sec-operacoes-log',
    name: 'Operações e Planejamento Logístico',
    companyId: 'comp-horizonte-sa',
    companyName: 'Grupo Horizonte Engenharia & Logística S.A.',
    managerName: 'Mariana Ferreira Santos',
    headcount: 42,
    pressureLevel: 'Alto',
    registeredDate: '2026-09-12',
    ownerId: 'system_default',
  },
  {
    id: 'sec-engenharia-manut',
    name: 'Engenharia de Manutenção e Qualidade',
    companyId: 'comp-vanguarda-tech',
    companyName: 'Vanguarda Soluções Industriais Ltda.',
    managerName: 'Roberto Almeida Costa',
    headcount: 28,
    pressureLevel: 'Moderado',
    registeredDate: '2026-09-16',
    ownerId: 'system_default',
  },
  {
    id: 'sec-rh-sst',
    name: 'Gestão de Pessoas, Clima e SST',
    companyId: 'comp-atlas-saude',
    companyName: 'Atlas Corporação Hospitalar & Diagnósticos',
    managerName: 'Dra. Helena Vasconcelos',
    headcount: 19,
    pressureLevel: 'Baixo',
    registeredDate: '2026-09-22',
    ownerId: 'system_default',
  },
];

export const INITIAL_COLLABORATORS: CollaboratorRecord[] = [
  {
    id: 'col-mariana-santos',
    webUid: 'WEB-COL-9041A',
    firstName: 'Mariana',
    lastName: 'Ferreira Santos',
    email: 'mariana.santos@horizonte.com.br',
    emailHint: 'Inicial do nome + sobrenome @horizonte.com.br',
    phone: '(11) 98741-2309',
    age: 36,
    birthDate: '1990-04-12',
    role: 'Gerente de Operações Logísticas',
    companyId: 'comp-horizonte-sa',
    companyName: 'Grupo Horizonte Engenharia & Logística S.A.',
    sectorId: 'sec-operacoes-log',
    sectorName: 'Operações e Planejamento Logístico',
    tenure: '4 anos e 6 meses',
    accountType: 'corporate',
    twoFactorEnabled: true,
    acceptedTerms: true,
    registeredDate: '2026-09-14',
    customFieldsMap: {
      matriculaCorporativa: 'MAT-2022-104',
      turnoTrabalho: 'Comercial (08h às 18h)',
      unidadeOperacional: 'Matriz São Paulo - SP',
    },
    ownerId: 'system_default',
  },
  {
    id: 'col-roberto-costa',
    webUid: 'WEB-COL-7728B',
    firstName: 'Roberto',
    lastName: 'Almeida Costa',
    email: 'roberto.costa@vanguardaind.com.br',
    emailHint: 'E-mail Google Workspace da planta Campinas',
    phone: '(19) 99214-8850',
    age: 41,
    birthDate: '1985-08-23',
    role: 'Coordenador de Engenharia e Qualidade',
    companyId: 'comp-vanguarda-tech',
    companyName: 'Vanguarda Soluções Industriais Ltda.',
    sectorId: 'sec-engenharia-manut',
    sectorName: 'Engenharia de Manutenção e Qualidade',
    tenure: '6 anos e 2 meses',
    accountType: 'google',
    twoFactorEnabled: true,
    googleUid: 'google-uid-roberto-7728b',
    acceptedTerms: true,
    registeredDate: '2026-09-18',
    customFieldsMap: {
      matriculaCorporativa: 'MAT-2020-039',
      turnoTrabalho: 'Turno 1 (06h às 14h)',
      unidadeOperacional: 'Planta Industrial Campinas - SP',
    },
    ownerId: 'system_default',
  },
  {
    id: 'col-helena-vasconcelos',
    webUid: 'WEB-COL-5519C',
    firstName: 'Helena',
    lastName: 'Vasconcelos',
    email: 'helena.vasconcelos@atlassaude.com.br',
    emailHint: 'Conta Google Corporativa atlassaude',
    phone: '(31) 98412-6610',
    age: 34,
    birthDate: '1992-01-30',
    role: 'Especialista em Diagnóstico Organizacional',
    companyId: 'comp-atlas-saude',
    companyName: 'Atlas Corporação Hospitalar & Diagnósticos',
    sectorId: 'sec-rh-sst',
    sectorName: 'Gestão de Pessoas, Clima e SST',
    tenure: '2 anos e 9 meses',
    accountType: 'google',
    twoFactorEnabled: true,
    googleUid: 'uid-google-corp-88219',
    acceptedTerms: true,
    registeredDate: '2026-09-24',
    customFieldsMap: {
      matriculaCorporativa: 'MAT-2024-211',
      turnoTrabalho: 'Híbrido Corporativo',
      unidadeOperacional: 'Unidade Savassi - BH',
    },
    ownerId: 'system_default',
  },
  {
    id: 'col-camila-andrade',
    webUid: 'WEB-COL-3310D',
    firstName: 'Camila',
    lastName: 'Nogueira Andrade',
    email: 'camila.andrade@gmail.com',
    emailHint: 'Conta Google com 2FA Ativo',
    phone: '(11) 99104-5521',
    age: 31,
    birthDate: '1995-03-19',
    role: 'Supervisora de Governança e Riscos',
    companyId: 'comp-horizonte-sa',
    companyName: 'Grupo Horizonte Engenharia & Logística S.A.',
    sectorId: 'sec-operacoes-log',
    sectorName: 'Operações e Planejamento Logístico',
    tenure: '3 anos e 1 mês',
    accountType: 'google',
    twoFactorEnabled: true,
    googleUid: 'google-uid-camila-3310d',
    acceptedTerms: true,
    registeredDate: '2026-09-26',
    customFieldsMap: {
      matriculaCorporativa: 'MAT-2023-310',
      turnoTrabalho: 'Híbrido Corporativo',
      unidadeOperacional: 'Matriz São Paulo - SP',
    },
    ownerId: 'system_default',
  },
  {
    id: 'col-lucas-prado',
    webUid: 'WEB-COL-1190E',
    firstName: 'Lucas',
    lastName: 'Martins Prado',
    email: 'lucas.prado@gmail.com',
    emailHint: 'Conta Google pendente de 2FA',
    phone: '(19) 98811-4092',
    age: 29,
    birthDate: '1997-11-05',
    role: 'Analista Sênior de Processos',
    companyId: 'comp-vanguarda-tech',
    companyName: 'Vanguarda Soluções Industriais Ltda.',
    sectorId: 'sec-engenharia-manut',
    sectorName: 'Engenharia de Manutenção e Qualidade',
    tenure: '1 ano e 8 meses',
    accountType: 'google',
    twoFactorEnabled: false,
    googleUid: 'google-uid-lucas-1190e',
    acceptedTerms: true,
    registeredDate: '2026-09-27',
    customFieldsMap: {
      matriculaCorporativa: 'MAT-2025-190',
      turnoTrabalho: 'Comercial (08h às 18h)',
      unidadeOperacional: 'Planta Industrial Campinas - SP',
    },
    ownerId: 'system_default',
  },
];

export const INITIAL_INTERVIEWS: InterviewRecord[] = [
  {
    id: 'int-diag-001',
    collaboratorId: 'col-mariana-santos',
    collaboratorWebUid: 'WEB-COL-9041A',
    managerName: 'Mariana Ferreira Santos',
    roleSector: 'Gerente de Operações Logísticas / Operações e Planejamento Logístico',
    companyName: 'Grupo Horizonte Engenharia & Logística S.A.',
    interviewDate: '2026-09-25',
    tenure: '4 anos e 6 meses',
    q1DemandsAndPressure:
      'As principais demandas concentram-se na expedição rodoviária nacional e consolidação de cargas críticas. Os períodos de maior pressão ocorrem na última semana de cada mês (fechamento de metas de SLA) e entre outubro e dezembro devido ao pico sazonal de varejo.',
    q2TaskDistribution:
      'As tarefas são distribuídas por célula regional e senioridade dos analistas. Utilizamos reuniões diárias de 15 minutos no início do turno para redistribuir rotas em atraso e balancear o volume de manifestos por operador.',
    q3FrequentConflicts:
      'Os conflitos mais frequentes ocorrem na passagem de turno entre recebimento e expedição por divergências de conferência física. São tratados imediatamente pelos líderes de célula com checagem conjunta no checklist digital.',
    q4ComplaintsHandling:
      'As insatisfações são acolhidas em rodadas quinzenais de feedback individual (1:1) e por meio do canal de escuta operacional. Todas as demandas recebem retorno formal em até 5 dias úteis.',
    q5SignificantChanges:
      'Implantamos há 60 dias o novo módulo de roteirização automatizada (WMS/TMS). O impacto inicial gerou curva de adaptação na equipe veterana, mas reduziu em 22% o tempo de espera em doca.',
    q6AttentionIndicators:
      'O volume de horas extras nos fechamentos mensais (média de 14h/mês por operador) e o absenteísmo pontual às segundas-feiras (3,8%) são os indicadores monitorados com maior rigor.',
    q7PreventiveMeasures:
      'Foram implantados rodízios de funções fisicamente intensas a cada 2 horas, contratação de 4 conferentes folguistas para cobrir picos sazonais e treinamento prático de liderança empática para supervisores.',
    extraAnswersMap: {},
    ownerId: 'system_default',
  },
  {
    id: 'int-diag-002',
    collaboratorId: 'col-roberto-costa',
    collaboratorWebUid: 'WEB-COL-7728B',
    managerName: 'Roberto Almeida Costa',
    roleSector: 'Coordenador de Engenharia e Qualidade / Engenharia de Manutenção e Qualidade',
    companyName: 'Vanguarda Soluções Industriais Ltda.',
    interviewDate: '2026-09-27',
    tenure: '6 anos e 2 meses',
    q1DemandsAndPressure:
      'Manutenção preventiva e corretiva de linhas automatizadas de estamparia e auditorias ISO 9001. A maior pressão ocorre durante paradas programadas de planta e quando há quebra não planejada de maquinário.',
    q2TaskDistribution:
      'Divisão por especialidade técnica (mecânica, elétrica, automação e metrologia) via ordens de serviço priorizadas por criticidade ABC no painel de manutenção.',
    q3FrequentConflicts:
      'Priorização entre Produção (que solicita liberação rápida de máquina) e Qualidade/Manutenção (que exige janela segura de calibração). Tratado via protocolo conjunto assinado pelos dois coordenadores.',
    q4ComplaintsHandling:
      'Reunião semanal de segurança e clima (DDS ampliado) e caixa física/digital de sugestões técnicas, com análise direta pela coordenação.',
    q5SignificantChanges:
      'Transição para relatórios digitais em tablets industriais na planta. Houve ganho de rastreabilidade e eliminação de retrabalho em prancheta de papel.',
    q6AttentionIndicators:
      'Turnover de técnicos de automação júnior (8% ao ano) devido à concorrência aquecida na região de Campinas.',
    q7PreventiveMeasures:
      'Plano de progressão técnica estruturado, climatização das oficinas de bancada e revisão da escala de plantão de fim de semana.',
    extraAnswersMap: {},
    ownerId: 'system_default',
  },
];

export const INITIAL_ADMINS: AdminMemberRecord[] = [
  {
    id: 'adm-master-mafersao',
    identifierType: 'google_uid',
    googleUid: 'google-uid-master-mafersao',
    corporateEmail: 'mafersao1100@gmail.com',
    displayName: 'Administrador Master (Google 2FA Ativo)',
    sectorRole: 'Diretoria de Diagnóstico & Governança TI',
    registeredDate: '2026-09-28',
    twoFactorVerified: true,
    ownerId: 'system_default',
  },
  {
    id: 'adm-helena-sst',
    identifierType: 'google_uid',
    googleUid: 'uid-google-corp-88219',
    corporateEmail: 'helena.vasconcelos@atlassaude.com.br',
    displayName: 'Dra. Helena Vasconcelos',
    sectorRole: 'Coordenação Setor de Administração & LGPD',
    registeredDate: '2026-09-24',
    twoFactorVerified: true,
    collaboratorId: 'col-helena-vasconcelos',
    collaboratorWebUid: 'WEB-COL-5519C',
    ownerId: 'system_default',
  },
];
